acq_funs = categorical({'EIIG', 'Dueling_UCB', 'MaxEntChallenge','DTS','random_acquisition_pref', ...
    'kernelselfsparring','maxvar_challenge', 'bivariate_EI', 'Brochu_EI', 'Thompson_challenge', 'random_acquisition_tour', ...
    'kernelselfsparring_tour', 'MVT','cBKG', 'TS_ALD','TSx_rands', 'randx_ALDs', 'rand_acq', ...
    'random', 'KSS_ALD', 'maxvar_ALD','pref_randx_ALDs','KSSx_rands','TME_sampling_binary', 'BALD_grid', 'Variance_gradient_grid', 'TS_maxvar'}');

names = categorical({'EIIG (Benavoli 2020)', 'Dueling UCB (Benavoli 2020)',...
    'MaxEntChallenge','Duel Thompson Sampling (modified from Gonzalez 2017)', ...
    'Random', 'Kernel Self-Sparring (Sui 2017)', 'Maximum Variance Challenge', ...
    'Bivariate Expected Improvement (Nielsen 2015)', 'Expected Improvement (Brochu 2010)', 'Dueling Thompson (Benavoli 2020)', 'Random', ...
    'Kernel Self-Sparring', 'Maximum Variance Tournament','cBKG', 'TS-ALD','Thompson Sampling', 'BALD', 'Random', ...
    'Random', 'KSS-ALD', 'MVC-ALD','BALD','Kernel Self-Sparring', 'Total Marginal Entropy sampling', 'BALD', 'Epistemic Uncertainty gradient','TS_maxvar'}');

names_citations = categorical({'EIIG \citep{Benavoli2020}', 'Dueling UCB \citep{Benavoli2020}', 'MaxEntChallenge', ...
    'Duel Thompson Sampling (modified from \citet{Gonzalez2017}','Random', 'KernelSelfSparring \citep{Sui2017}', ...
    'Maximum Variance Challenge', 'Bivariate Expected Improvement \citep{Nielsen2015}', 'Expected Improvement \citep{Brochu2010a}',...
    'Dueling Thompson \citep{Benavoli2020}', 'Random', 'KernelSelfSparring \citep{Sui2017}', 'Maximum Variance Tournament', ...
    'cBKG', 'TS-ALD','Thompson Sampling', 'BALD', 'Random','random', 'KSS-ALD', 'MVC-ALD','pref_randx_ALDs','KSSx_rands', 'TME sampling', ...
    'BALD (\citep{Houlsby2011})', 'Epistemic Uncertainty gradient','TS_maxvar'}');

short_names=  categorical({'EIIG', 'UCB', 'MEC','DTS','Random', 'KSS', 'MVC', 'BEI', 'EI', 'D. Thompson', 'Random', 'KSS','MVT', ...
    'cBKG', 'TS_ALD','TSx_rands', 'randx_ALDs', 'rand_acq','Random', 'KSS-ALD', 'MVC-ALD','BALD','KSS','TME sampling', 'BALD', ...
    'Epistemic Uncertainty gradient','TS_maxvar'}');

T = table(acq_funs, names,names_citations, short_names);
save('/home/tfauvel/Documents/BO_toolbox/Acquisition_funs_table','T')



